ARG version
FROM almalinux:${version:-8}
ARG COURSE="DOCKER" \
    TRAINER="vinod" \
    DURATION="lifetime"
RUN echo "triner is ${TRAINER}, version is ${version}" # try to find here you can not access the version varibale
CMD ["sleep","100"]